package com.astrologyvedic.app.ui.navigation

sealed class Routes(val route: String) {
    // Bottom navigation tabs
    data object Home : Routes("home")
    data object Services : Routes("services")
    data object Chat : Routes("chat")
    data object Calculators : Routes("calculators")
    data object Profile : Routes("profile")

    // Browse / tools
    data object Explore : Routes("explore")
    data object Tools : Routes("calculators")

    // Core features
    data object Kundli : Routes("kundli")
    data object Daily : Routes("daily")
    data object Match : Routes("match")
    data object Panchang : Routes("panchang")
    data object Numerology : Routes("numerology")
    data object PalmReading : Routes("palm_reading")
    data object Tarot : Routes("tarot")
    data object MantraCounter : Routes("mantra_counter")
    data object RahuKaal : Routes("rahu_kaal")
    data object Choghadiya : Routes("choghadiya")
    data object Hora : Routes("hora")
    data object SadeSati : Routes("sade_sati")
    data object Kaalsarp : Routes("kaalsarp")
    data object Muhurat : Routes("muhurat")
    data object Gemstone : Routes("gemstone")
    data object LoveCompatibility : Routes("love_compatibility")
    data object Festivals : Routes("festivals")
    data object BabyNames : Routes("baby_names")
    data object Meditation : Routes("meditation")
    data object Prayers : Routes("prayers")
    data object PujaGuide : Routes("puja_guide")
    data object HomaGuide : Routes("homa_guide")
    data object VratCalendar : Routes("vrat_calendar")
    data object TempleFinder : Routes("temple_finder")
    data object KpAstrology : Routes("kp_astrology")
    data object LalKitab : Routes("lal_kitab")
    data object Western : Routes("western")
    data object ChineseZodiac : Routes("chinese_zodiac")
    data object Nadi : Routes("nadi")
    data object Navamsa : Routes("navamsa")
    data object Dasamsa : Routes("dasamsa")
    data object VargaCharts : Routes("varga_charts")
    data object PastLife : Routes("past_life")
    data object Pathfinder : Routes("pathfinder")
    data object FaceReading : Routes("face_reading")
    data object YogaDetection : Routes("yoga_detection")
    data object Celebrity : Routes("celebrity")
    data object ChartComparison : Routes("chart_comparison")
    data object BirthRectification : Routes("birth_rectification")
    data object StockAstrology : Routes("stock_astrology")
    data object HoroscopeShare : Routes("horoscope_share")
    data object Lucky : Routes("lucky")
    data object LifeReport : Routes("life_report")
    data object Vastu : Routes("vastu")
    data object Timeline : Routes("timeline")
    data object Transit : Routes("transit")
    data object GunaMilan : Routes("guna_milan")
    data object DailyMantra : Routes("daily_mantra")
    data object SunriseSunset : Routes("sunrise_sunset")
    data object Ayanamsa : Routes("ayanamsa")
    data object NameMatch : Routes("name_match")
    data object Porutham : Routes("porutham")
    data object AiChat : Routes("ai_chat")
    data object Settings : Routes("settings")
    data object Notifications : Routes("notifications")
    data object About : Routes("about")
    data object HelpSupport : Routes("help_support")
    data object Language : Routes("language")
    data object SavedCharts : Routes("saved_charts")
    data object ReportHistory : Routes("report_history")
    data object EditProfile : Routes("edit_profile")
}
