package com.astrologyvedic.app.ui.theme

import androidx.compose.ui.graphics.Color

// Material You - Indigo seed color (fallback for devices without dynamic color)

// Light Theme Colors
val md_theme_light_primary = Color(0xFF4355B9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDEE0FF)
val md_theme_light_onPrimaryContainer = Color(0xFF00105C)
val md_theme_light_secondary = Color(0xFF5B5D72)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE0E1F9)
val md_theme_light_onSecondaryContainer = Color(0xFF181A2C)
val md_theme_light_tertiary = Color(0xFF77536D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD7F1)
val md_theme_light_onTertiaryContainer = Color(0xFF2D1228)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_outlineVariant = Color(0xFFC7C5D0)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inverseOnSurface = Color(0xFFF3EFF4)
val md_theme_light_inversePrimary = Color(0xFFBBC3FF)
val md_theme_light_surfaceTint = Color(0xFF4355B9)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFFBBC3FF)
val md_theme_dark_onPrimary = Color(0xFF0B2278)
val md_theme_dark_primaryContainer = Color(0xFF293CA0)
val md_theme_dark_onPrimaryContainer = Color(0xFFDEE0FF)
val md_theme_dark_secondary = Color(0xFFC4C5DD)
val md_theme_dark_onSecondary = Color(0xFF2D2F42)
val md_theme_dark_secondaryContainer = Color(0xFF434559)
val md_theme_dark_onSecondaryContainer = Color(0xFFE0E1F9)
val md_theme_dark_tertiary = Color(0xFFE5BAD8)
val md_theme_dark_onTertiary = Color(0xFF44263D)
val md_theme_dark_tertiaryContainer = Color(0xFF5D3C55)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD7F1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE4E1E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE4E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val md_theme_dark_outline = Color(0xFF90909A)
val md_theme_dark_outlineVariant = Color(0xFF46464F)
val md_theme_dark_inverseSurface = Color(0xFFE4E1E6)
val md_theme_dark_inverseOnSurface = Color(0xFF303034)
val md_theme_dark_inversePrimary = Color(0xFF4355B9)
val md_theme_dark_surfaceTint = Color(0xFFBBC3FF)

// Semantic colors
val Success = Color(0xFF2E7D32)
val SuccessContainer = Color(0xFFE8F5E9)
val Warning = Color(0xFFF57C00)
val WarningContainer = Color(0xFFFFF3E0)
val Info = Color(0xFF1565C0)
val InfoContainer = Color(0xFFE3F2FD)

// Planet colors for charts
val PlanetSun = Color(0xFFF9A825)
val PlanetMoon = Color(0xFF90CAF9)
val PlanetMars = Color(0xFFE53935)
val PlanetMercury = Color(0xFF43A047)
val PlanetJupiter = Color(0xFFFBC02D)
val PlanetVenus = Color(0xFFEC407A)
val PlanetSaturn = Color(0xFF5C6BC0)
val PlanetRahu = Color(0xFF546E7A)
val PlanetKetu = Color(0xFF8D6E63)

// Feature accent colors (used in tool grid icons matching Stitch mockup)
val AccentYellow = Color(0xFFFBC02D)
val AccentIndigo = Color(0xFF3F51B5)
val AccentTeal = Color(0xFF00897B)
val AccentOrange = Color(0xFFF4511E)
